// components/GameCanvas.tsx
'use client'

import { useEffect, useRef, useState } from 'react'
import { GameEngine } from '@/lib/game/core/GameEngine'
import styles from './GameCanvas.module.css'

type GameState = 'loading' | 'ready' | 'playing' | 'paused' | 'gameover'

/**
 * 게임 캔버스 컴포넌트
 * 
 * 게임 초기화 시퀀스:
 * 1. 컴포넌트 마운트 (useEffect)
 * 2. Canvas 크기 설정
 * 3. GameEngine 생성 (STEP 1: constructor)
 * 4. 리소스 로딩 시작 (STEP 2: loadResources)
 * 5. 로딩 완료 후 'ready' 상태로 전환
 * 6. 사용자가 "게임 시작" 버튼 클릭
 * 7. 게임 루프 시작 (STEP 3: start)
 */
export default function GameCanvas() {
    const canvasRef = useRef<HTMLCanvasElement>(null)
    const gameEngineRef = useRef<GameEngine | null>(null)

    const [gameState, setGameState] = useState<GameState>('loading')
    const [loadingProgress, setLoadingProgress] = useState(0)

    /**
     * 컴포넌트 마운트 시 게임 초기화 시퀀스 시작
     */
    useEffect(() => {
        console.log('🎬 [SEQUENCE START] GameCanvas mounted, starting initialization...')

        if (!canvasRef.current) return

        const canvas = canvasRef.current

        // Canvas 크기 설정
        const resizeCanvas = () => {
            canvas.width = window.innerWidth
            canvas.height = window.innerHeight

            if (gameEngineRef.current) {
                gameEngineRef.current.resize(window.innerWidth, window.innerHeight)
            }
        }

        resizeCanvas()
        window.addEventListener('resize', resizeCanvas)

        // 게임 초기화 시퀀스 실행
        initializeGameSequence(canvas)

        // ESC 키로 일시정지
        const handleEscKey = (e: KeyboardEvent) => {
            if (e.code === 'Escape') {
                if (gameState === 'playing') {
                    gameEngineRef.current?.pause()
                    setGameState('paused')
                } else if (gameState === 'paused') {
                    gameEngineRef.current?.resume()
                    setGameState('playing')
                }
            }
        }

        window.addEventListener('keydown', handleEscKey)

        // Cleanup
        return () => {
            console.log('🧹 Cleaning up GameCanvas...')
            window.removeEventListener('resize', resizeCanvas)
            window.removeEventListener('keydown', handleEscKey)
            gameEngineRef.current?.destroy()
        }
    }, []) // gameState를 의존성에서 제거하고 ref 사용

    /**
     * 게임 초기화 시퀀스
     * STEP 1 → STEP 2 → (사용자 대기) → STEP 3
     */
    const initializeGameSequence = async (canvas: HTMLCanvasElement) => {
        try {
            // ========== STEP 1: GameEngine 생성 ==========
            console.log('🎮 [SEQUENCE] Creating GameEngine instance...')
            const gameEngine = new GameEngine(canvas)
            gameEngineRef.current = gameEngine

            // ========== STEP 2: 리소스 로딩 ==========
            console.log('📦 [SEQUENCE] Starting resource loading...')

            // 로딩 진행률 모니터링
            gameEngine.resourceLoader.onProgress((progress: number) => {
                setLoadingProgress(progress)
                console.log(`📊 Loading progress: ${progress.toFixed(0)}%`)
            })

            // 로딩 완료 콜백
            gameEngine.resourceLoader.onComplete(() => {
                console.log('✅ [SEQUENCE] Resources loaded, transitioning to READY state')
                setGameState('ready')
            })

            // 리소스 로드 시작
            await gameEngine.loadResources()

            console.log('⏸️  [SEQUENCE] Waiting for user to click "Start Game" button...')

            // ========== STEP 3: start() 호출은 startGame() 함수에서 실행 ==========

        } catch (error) {
            console.error('❌ [SEQUENCE ERROR] Failed to initialize game:', error)
            // TODO: 에러 상태 처리
        }
    }

    /**
     * STEP 3: 게임 시작 (사용자가 버튼 클릭 시)
     */
    const startGame = () => {
        console.log('🚀 [SEQUENCE] User clicked START, launching game loop...')

        if (gameEngineRef.current) {
            gameEngineRef.current.start()
            setGameState('playing')
            console.log('✅ [SEQUENCE COMPLETE] Game is now running!')
        }
    }

    /**
     * 게임 재개
     */
    const resumeGame = () => {
        if (gameEngineRef.current) {
            gameEngineRef.current.resume()
            setGameState('playing')
        }
    }

    return (
        <div className={styles.gameWrapper}>
            {/* 로딩 화면 */}
            {gameState === 'loading' && (
                <div className={styles.loadingScreen}>
                    <div className={styles.loadingContent}>
                        <h1>🧟 Zombie MMORPG</h1>
                        <div className={styles.loadingBar}>
                            <div
                                className={styles.loadingProgress}
                                style={{ width: `${loadingProgress}%` }}
                            />
                        </div>
                        <p>{loadingProgress.toFixed(0)}% 로딩 중...</p>
                    </div>
                </div>
            )}

            {/* 시작 버튼 (로딩 완료 후) */}
            {gameState === 'ready' && (
                <div className={styles.startScreen}>
                    <div className={styles.startContent}>
                        <h1>🧟 Zombie MMORPG</h1>
                        <p className={styles.subtitle}>오픈 월드 쿼터뷰 액션 게임</p>
                        <button onClick={startGame} className={styles.btnStart}>
                            게임 시작
                        </button>
                    </div>
                </div>
            )}

            {/* 일시정지 화면 */}
            {gameState === 'paused' && (
                <div className={styles.pauseScreen}>
                    <div className={styles.pauseContent}>
                        <h2>일시정지</h2>
                        <button onClick={resumeGame} className={styles.btnResume}>
                            계속하기
                        </button>
                    </div>
                </div>
            )}

            {/* 게임 Canvas */}
            <canvas
                ref={canvasRef}
                className={`${styles.gameCanvas} ${gameState === 'paused' ? styles.blur : ''}`}
            />
        </div>
    )
}

// components/GameCanvas.vue
<template>
  <div class="game-wrapper">
    <!-- 로딩 화면 -->
    <div v-if="gameState === 'loading'" class="loading-screen">
      <div class="loading-content">
        <h1>🧟 Zombie MMORPG</h1>
        <div class="loading-bar">
          <div
            class="loading-progress"
            :style="{ width: `${loadingProgress}%` }"
          ></div>
        </div>
        <p>{{ loadingProgress.toFixed(0) }}% 로딩 중...</p>
      </div>
    </div>

    <!-- 일시정지 화면 -->
    <div v-if="gameState === 'paused'" class="pause-screen">
      <div class="pause-content">
        <h2>일시정지</h2>
        <button @click="resumeGame" class="btn-resume">계속하기</button>
      </div>
    </div>

    <!-- 게임 Canvas -->
    <canvas
      ref="gameCanvas"
      class="game-canvas"
      :class="{ blur: gameState === 'paused' }"
    ></canvas>

    <!-- 시작 버튼 (로딩 완료 후) -->
    <div v-if="gameState === 'ready'" class="start-screen">
      <div class="start-content">
        <h1>🧟 Zombie MMORPG</h1>
        <p class="subtitle">오픈 월드 쿼터뷰 액션 게임</p>
        <button @click="startGame" class="btn-start">게임 시작</button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from "vue"
import { GameEngine } from "~/composables/useGameEngine"

const gameCanvas = ref<HTMLCanvasElement | null>(null)
let gameEngine: GameEngine | null = null

const gameState = ref<"loading" | "ready" | "playing" | "paused" | "gameover">(
  "loading",
)
const loadingProgress = ref(0)

onMounted(async () => {
  if (!gameCanvas.value) return

  // Canvas 크기 설정
  resizeCanvas()
  window.addEventListener("resize", resizeCanvas)

  // 게임 엔진 초기화
  gameEngine = new GameEngine(gameCanvas.value)

  // 리소스 로딩 진행률 모니터링
  gameEngine.resourceLoader.onProgress((progress: number) => {
    loadingProgress.value = progress
  })

  gameEngine.resourceLoader.onComplete(() => {
    gameState.value = "ready"
  })

  // 리소스 로드 시작
  await gameEngine.loadResources()

  // ESC 키로 일시정지
  window.addEventListener("keydown", handleEscKey)
})

onUnmounted(() => {
  window.removeEventListener("resize", resizeCanvas)
  window.removeEventListener("keydown", handleEscKey)
  gameEngine?.destroy()
})

function resizeCanvas() {
  if (!gameCanvas.value) return

  gameCanvas.value.width = window.innerWidth
  gameCanvas.value.height = window.innerHeight

  if (gameEngine) {
    gameEngine.resize(window.innerWidth, window.innerHeight)
  }
}

function startGame() {
  if (gameEngine) {
    gameEngine.start()
    gameState.value = "playing"
  }
}

function resumeGame() {
  if (gameEngine) {
    gameEngine.resume()
    gameState.value = "playing"
  }
}

function handleEscKey(e: KeyboardEvent) {
  if (e.code === "Escape") {
    if (gameState.value === "playing") {
      gameEngine?.pause()
      gameState.value = "paused"
    } else if (gameState.value === "paused") {
      resumeGame()
    }
  }
}
</script>

<style scoped>
.game-wrapper {
  position: relative;
  width: 100vw;
  height: 100vh;
  overflow: hidden;
  background: #000;
}

.game-canvas {
  display: block;
  image-rendering: crisp-edges;
  image-rendering: pixelated;
  transition: filter 0.3s ease;
}

.game-canvas.blur {
  filter: blur(5px);
}

/* 로딩 화면 */
.loading-screen {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  background: linear-gradient(135deg, #1a1a1a 0%, #2d1810 100%);
  z-index: 100;
}

.loading-content {
  text-align: center;
  color: #fff;
}

.loading-content h1 {
  font-size: 48px;
  margin-bottom: 30px;
  text-shadow: 0 0 20px rgba(255, 0, 0, 0.5);
}

.loading-bar {
  width: 400px;
  height: 20px;
  background: rgba(255, 255, 255, 0.1);
  border-radius: 10px;
  overflow: hidden;
  margin: 20px auto;
  border: 2px solid rgba(255, 255, 255, 0.3);
}

.loading-progress {
  height: 100%;
  background: linear-gradient(90deg, #ff4444 0%, #ff8844 100%);
  transition: width 0.3s ease;
  box-shadow: 0 0 10px rgba(255, 68, 68, 0.5);
}

/* 시작 화면 */
.start-screen {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  background: linear-gradient(135deg, #1a1a1a 0%, #2d1810 100%);
  z-index: 100;
}

.start-content {
  text-align: center;
  color: #fff;
}

.start-content h1 {
  font-size: 64px;
  margin-bottom: 10px;
  text-shadow: 0 0 20px rgba(255, 0, 0, 0.5);
  animation: pulse 2s ease-in-out infinite;
}

.subtitle {
  font-size: 18px;
  color: #aaa;
  margin-bottom: 40px;
}

.btn-start {
  padding: 15px 40px;
  font-size: 24px;
  font-weight: bold;
  color: #fff;
  background: linear-gradient(135deg, #ff4444 0%, #cc0000 100%);
  border: none;
  border-radius: 10px;
  cursor: pointer;
  box-shadow: 0 5px 15px rgba(255, 68, 68, 0.4);
  transition: all 0.3s ease;
}

.btn-start:hover {
  transform: translateY(-2px);
  box-shadow: 0 8px 20px rgba(255, 68, 68, 0.6);
}

.btn-start:active {
  transform: translateY(0);
}

/* 일시정지 화면 */
.pause-screen {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  background: rgba(0, 0, 0, 0.7);
  z-index: 100;
}

.pause-content {
  text-align: center;
  color: #fff;
}

.pause-content h2 {
  font-size: 48px;
  margin-bottom: 30px;
  text-shadow: 0 0 10px rgba(255, 255, 255, 0.5);
}

.btn-resume {
  padding: 12px 30px;
  font-size: 20px;
  font-weight: bold;
  color: #fff;
  background: linear-gradient(135deg, #4444ff 0%, #0000cc 100%);
  border: none;
  border-radius: 8px;
  cursor: pointer;
  box-shadow: 0 5px 15px rgba(68, 68, 255, 0.4);
  transition: all 0.3s ease;
}

.btn-resume:hover {
  transform: translateY(-2px);
  box-shadow: 0 8px 20px rgba(68, 68, 255, 0.6);
}

@keyframes pulse {
  0%,
  100% {
    transform: scale(1);
  }
  50% {
    transform: scale(1.05);
  }
}
</style>
